apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-v2
  labels:
    app: guestbook-ui
    version: "2.0"
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook-ui
      version: "2.0"
      serving: "true"
  template:
    metadata:
      labels:
        app: guestbook-ui
        version: "2.0"
        serving: "true"
        visualize: "true"
      annotations:
        visualizer/uses: helloworld-service,guestbook-service,redis
    spec:
      containers:
      - name: guestbook-ui
        image: sanjeevrg/guestbook-ui-istio:2.0
        env:
        - name: BACKEND_GUESTBOOK_SERVICE_URL
          value: http://guestbook-service/messages
        livenessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /actuator/health
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        ports:
        - name: http
          containerPort: 8080