---
apiVersion: v1
kind: Service
metadata:
  name: espresso-shop-reviews-svc
spec:
  selector:
    app: espresso-shop-reviews
  type: LoadBalancer
  ports:
  - port: 8092
    targetPort: 80
    name: http