apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-service-v1
  labels:
    app: guestbook-service
    version: "1.0"
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook-service
      version: "1.0"
      serving: "true"
  template:
    metadata:
      labels:
        app: guestbook-service
        serving: "true"
        version: "1.0"
        visualize: "true"
    spec:
      serviceAccountName: guestbook-service
      containers:
      - name: guestbook-service
        image: sanjeevrg/guestbook-service-istio:1.0
        livenessProbe:
          initialDelaySeconds: 90
          exec:
            command:
            - wget
            - -qO-
            - http://localhost:8080/actuator/health
        readinessProbe:
          exec:
            command:
            - wget
            - -qO-
            - http://localhost:8080/
        ports:
        - containerPort: 8080
          name: http
---
kind: Service
apiVersion: v1
metadata:
  name: guestbook-service
  labels:
    app: guestbook-service
    visualize: "true"
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: guestbook-service
    serving: "true"