apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-v1
  labels:
    app: guestbook-ui
    version: "1.0"
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook-ui
      version: "1.0"
      serving: "true"
  template:
    metadata:
      labels:
        app: guestbook-ui
        version: "1.0"
        serving: "true"
        visualize: "true"
      annotations:
        visualizer/uses: helloworld-service,guestbook-service,redis
    spec:
      serviceAccount: guestbook-ui
      containers:
      - name: guestbook-ui
        image: sanjeevrg/guestbook-ui-istio:1.0
        env:
        - name: BACKEND_GUESTBOOK_SERVICE_URL
          value: http://guestbook-service/messages
        livenessProbe:
          initialDelaySeconds: 60
          exec:
            command:
            - wget
            - -qO-
            - http://localhost:8080/actuator/health
        readinessProbe:
          exec:
            command:
            - wget
            - -qO-
            - http://localhost:8080/
        ports:
        - name: http
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: guestbook-ui
  labels:
    app: guestbook-ui
    visualize: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: guestbook-ui
    serving: "true"